package com.example.schoolmanagement.service.aiquery;

public enum AiInformationIntent {
    ASK_STUDENT_PROFILE,
    ASK_STUDENT_CLASS,
    ASK_PARENT_CONTACT,
    ASK_STUDENTS_BY_CLASS,
    ASK_CLASS_SIZE,
    ASK_STUDENT_SUBJECT_SCORE,
    ASK_STUDENT_AVERAGE_SCORE,
    ASK_WEAK_STUDENTS_BY_CLASS_SUBJECT,
    ASK_TOP_STUDENTS_BY_CLASS,
    ASK_LOWEST_STUDENT_BY_CLASS,
    ASK_STUDENT_RANK_IN_CLASS,
    ASK_STUDENT_ATTENDANCE,
    ASK_CLASS_ATTENDANCE_OVERVIEW,
    ASK_STUDENT_TIMETABLE,
    ASK_STUDENT_OVERVIEW,
    ASK_SCHOOL_STATISTICS,
    ASK_STUDENT_PREDICTION,
    ASK_TEACHER_ASSIGNMENTS,
    ASK_TEACHER_TIMETABLE,
    ASK_TEACHER_WORKLOAD,
    ASK_TEACHER_PERFORMANCE_OVERVIEW,

    // Legacy intents (keep for compatibility with existing dispatch/services)
    CLASS_OVERVIEW,
    CLASS_RISK_STUDENTS_COUNT,
    CLASS_SUBJECT_RISK_COUNT,
    STUDENT_WEAK_SUBJECTS,
    TEACHER_ASSIGNMENTS,
    HOMEROOM_LOOKUP,
    SCHOOL_RISK_OVERVIEW,
    UNKNOWN
}

